/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSalesOrdersRouteImport } from './routes/_authenticated/sales-orders'
import { Route as AuthenticatedQcRouteImport } from './routes/_authenticated/qc'
import { Route as AuthenticatedProductionPlanningRouteImport } from './routes/_authenticated/production-planning'
import { Route as AuthenticatedProductionRouteImport } from './routes/_authenticated/production'
import { Route as AuthenticatedOperatorsRouteImport } from './routes/_authenticated/operators'
import { Route as AuthenticatedMaterialRouteImport } from './routes/_authenticated/material'
import { Route as AuthenticatedEngineeringRouteImport } from './routes/_authenticated/engineering'
import { Route as AuthenticatedDeliveryRouteImport } from './routes/_authenticated/delivery'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSalesOrdersNewRouteImport } from './routes/_authenticated/sales-orders.new'
import { Route as AuthenticatedSalesOrdersIdRouteImport } from './routes/_authenticated/sales-orders.$id'
import { Route as AuthenticatedEngineeringWorkloadRouteImport } from './routes/_authenticated/engineering.workload'
import { Route as AuthenticatedEngineeringIdRouteImport } from './routes/_authenticated/engineering.$id'
import { Route as AuthenticatedDeliveryScheduleRouteImport } from './routes/_authenticated/delivery.schedule'
import { Route as AuthenticatedDeliveryIdRouteImport } from './routes/_authenticated/delivery.$id'
import { Route as AuthenticatedSalesOrdersIdEditRouteImport } from './routes/_authenticated/sales-orders.$id.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSalesOrdersRoute =
  AuthenticatedSalesOrdersRouteImport.update({
    id: '/sales-orders',
    path: '/sales-orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQcRoute = AuthenticatedQcRouteImport.update({
  id: '/qc',
  path: '/qc',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductionPlanningRoute =
  AuthenticatedProductionPlanningRouteImport.update({
    id: '/production-planning',
    path: '/production-planning',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductionRoute = AuthenticatedProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperatorsRoute = AuthenticatedOperatorsRouteImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaterialRoute = AuthenticatedMaterialRouteImport.update({
  id: '/material',
  path: '/material',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEngineeringRoute =
  AuthenticatedEngineeringRouteImport.update({
    id: '/engineering',
    path: '/engineering',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeliveryRoute = AuthenticatedDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesOrdersNewRoute =
  AuthenticatedSalesOrdersNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedSalesOrdersRoute,
  } as any)
const AuthenticatedSalesOrdersIdRoute =
  AuthenticatedSalesOrdersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedSalesOrdersRoute,
  } as any)
const AuthenticatedEngineeringWorkloadRoute =
  AuthenticatedEngineeringWorkloadRouteImport.update({
    id: '/workload',
    path: '/workload',
    getParentRoute: () => AuthenticatedEngineeringRoute,
  } as any)
const AuthenticatedEngineeringIdRoute =
  AuthenticatedEngineeringIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedEngineeringRoute,
  } as any)
const AuthenticatedDeliveryScheduleRoute =
  AuthenticatedDeliveryScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => AuthenticatedDeliveryRoute,
  } as any)
const AuthenticatedDeliveryIdRoute = AuthenticatedDeliveryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedDeliveryRoute,
} as any)
const AuthenticatedSalesOrdersIdEditRoute =
  AuthenticatedSalesOrdersIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedSalesOrdersIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/delivery': typeof AuthenticatedDeliveryRouteWithChildren
  '/engineering': typeof AuthenticatedEngineeringRouteWithChildren
  '/material': typeof AuthenticatedMaterialRoute
  '/operators': typeof AuthenticatedOperatorsRoute
  '/production': typeof AuthenticatedProductionRoute
  '/production-planning': typeof AuthenticatedProductionPlanningRoute
  '/qc': typeof AuthenticatedQcRoute
  '/sales-orders': typeof AuthenticatedSalesOrdersRouteWithChildren
  '/delivery/$id': typeof AuthenticatedDeliveryIdRoute
  '/delivery/schedule': typeof AuthenticatedDeliveryScheduleRoute
  '/engineering/$id': typeof AuthenticatedEngineeringIdRoute
  '/engineering/workload': typeof AuthenticatedEngineeringWorkloadRoute
  '/sales-orders/$id': typeof AuthenticatedSalesOrdersIdRouteWithChildren
  '/sales-orders/new': typeof AuthenticatedSalesOrdersNewRoute
  '/sales-orders/$id/edit': typeof AuthenticatedSalesOrdersIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/delivery': typeof AuthenticatedDeliveryRouteWithChildren
  '/engineering': typeof AuthenticatedEngineeringRouteWithChildren
  '/material': typeof AuthenticatedMaterialRoute
  '/operators': typeof AuthenticatedOperatorsRoute
  '/production': typeof AuthenticatedProductionRoute
  '/production-planning': typeof AuthenticatedProductionPlanningRoute
  '/qc': typeof AuthenticatedQcRoute
  '/sales-orders': typeof AuthenticatedSalesOrdersRouteWithChildren
  '/delivery/$id': typeof AuthenticatedDeliveryIdRoute
  '/delivery/schedule': typeof AuthenticatedDeliveryScheduleRoute
  '/engineering/$id': typeof AuthenticatedEngineeringIdRoute
  '/engineering/workload': typeof AuthenticatedEngineeringWorkloadRoute
  '/sales-orders/$id': typeof AuthenticatedSalesOrdersIdRouteWithChildren
  '/sales-orders/new': typeof AuthenticatedSalesOrdersNewRoute
  '/sales-orders/$id/edit': typeof AuthenticatedSalesOrdersIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/delivery': typeof AuthenticatedDeliveryRouteWithChildren
  '/_authenticated/engineering': typeof AuthenticatedEngineeringRouteWithChildren
  '/_authenticated/material': typeof AuthenticatedMaterialRoute
  '/_authenticated/operators': typeof AuthenticatedOperatorsRoute
  '/_authenticated/production': typeof AuthenticatedProductionRoute
  '/_authenticated/production-planning': typeof AuthenticatedProductionPlanningRoute
  '/_authenticated/qc': typeof AuthenticatedQcRoute
  '/_authenticated/sales-orders': typeof AuthenticatedSalesOrdersRouteWithChildren
  '/_authenticated/delivery/$id': typeof AuthenticatedDeliveryIdRoute
  '/_authenticated/delivery/schedule': typeof AuthenticatedDeliveryScheduleRoute
  '/_authenticated/engineering/$id': typeof AuthenticatedEngineeringIdRoute
  '/_authenticated/engineering/workload': typeof AuthenticatedEngineeringWorkloadRoute
  '/_authenticated/sales-orders/$id': typeof AuthenticatedSalesOrdersIdRouteWithChildren
  '/_authenticated/sales-orders/new': typeof AuthenticatedSalesOrdersNewRoute
  '/_authenticated/sales-orders/$id/edit': typeof AuthenticatedSalesOrdersIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/customers'
    | '/dashboard'
    | '/delivery'
    | '/engineering'
    | '/material'
    | '/operators'
    | '/production'
    | '/production-planning'
    | '/qc'
    | '/sales-orders'
    | '/delivery/$id'
    | '/delivery/schedule'
    | '/engineering/$id'
    | '/engineering/workload'
    | '/sales-orders/$id'
    | '/sales-orders/new'
    | '/sales-orders/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/customers'
    | '/dashboard'
    | '/delivery'
    | '/engineering'
    | '/material'
    | '/operators'
    | '/production'
    | '/production-planning'
    | '/qc'
    | '/sales-orders'
    | '/delivery/$id'
    | '/delivery/schedule'
    | '/engineering/$id'
    | '/engineering/workload'
    | '/sales-orders/$id'
    | '/sales-orders/new'
    | '/sales-orders/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/delivery'
    | '/_authenticated/engineering'
    | '/_authenticated/material'
    | '/_authenticated/operators'
    | '/_authenticated/production'
    | '/_authenticated/production-planning'
    | '/_authenticated/qc'
    | '/_authenticated/sales-orders'
    | '/_authenticated/delivery/$id'
    | '/_authenticated/delivery/schedule'
    | '/_authenticated/engineering/$id'
    | '/_authenticated/engineering/workload'
    | '/_authenticated/sales-orders/$id'
    | '/_authenticated/sales-orders/new'
    | '/_authenticated/sales-orders/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sales-orders': {
      id: '/_authenticated/sales-orders'
      path: '/sales-orders'
      fullPath: '/sales-orders'
      preLoaderRoute: typeof AuthenticatedSalesOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qc': {
      id: '/_authenticated/qc'
      path: '/qc'
      fullPath: '/qc'
      preLoaderRoute: typeof AuthenticatedQcRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production-planning': {
      id: '/_authenticated/production-planning'
      path: '/production-planning'
      fullPath: '/production-planning'
      preLoaderRoute: typeof AuthenticatedProductionPlanningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operators': {
      id: '/_authenticated/operators'
      path: '/operators'
      fullPath: '/operators'
      preLoaderRoute: typeof AuthenticatedOperatorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/material': {
      id: '/_authenticated/material'
      path: '/material'
      fullPath: '/material'
      preLoaderRoute: typeof AuthenticatedMaterialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/engineering': {
      id: '/_authenticated/engineering'
      path: '/engineering'
      fullPath: '/engineering'
      preLoaderRoute: typeof AuthenticatedEngineeringRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/delivery': {
      id: '/_authenticated/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof AuthenticatedDeliveryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales-orders/new': {
      id: '/_authenticated/sales-orders/new'
      path: '/new'
      fullPath: '/sales-orders/new'
      preLoaderRoute: typeof AuthenticatedSalesOrdersNewRouteImport
      parentRoute: typeof AuthenticatedSalesOrdersRoute
    }
    '/_authenticated/sales-orders/$id': {
      id: '/_authenticated/sales-orders/$id'
      path: '/$id'
      fullPath: '/sales-orders/$id'
      preLoaderRoute: typeof AuthenticatedSalesOrdersIdRouteImport
      parentRoute: typeof AuthenticatedSalesOrdersRoute
    }
    '/_authenticated/engineering/workload': {
      id: '/_authenticated/engineering/workload'
      path: '/workload'
      fullPath: '/engineering/workload'
      preLoaderRoute: typeof AuthenticatedEngineeringWorkloadRouteImport
      parentRoute: typeof AuthenticatedEngineeringRoute
    }
    '/_authenticated/engineering/$id': {
      id: '/_authenticated/engineering/$id'
      path: '/$id'
      fullPath: '/engineering/$id'
      preLoaderRoute: typeof AuthenticatedEngineeringIdRouteImport
      parentRoute: typeof AuthenticatedEngineeringRoute
    }
    '/_authenticated/delivery/schedule': {
      id: '/_authenticated/delivery/schedule'
      path: '/schedule'
      fullPath: '/delivery/schedule'
      preLoaderRoute: typeof AuthenticatedDeliveryScheduleRouteImport
      parentRoute: typeof AuthenticatedDeliveryRoute
    }
    '/_authenticated/delivery/$id': {
      id: '/_authenticated/delivery/$id'
      path: '/$id'
      fullPath: '/delivery/$id'
      preLoaderRoute: typeof AuthenticatedDeliveryIdRouteImport
      parentRoute: typeof AuthenticatedDeliveryRoute
    }
    '/_authenticated/sales-orders/$id/edit': {
      id: '/_authenticated/sales-orders/$id/edit'
      path: '/edit'
      fullPath: '/sales-orders/$id/edit'
      preLoaderRoute: typeof AuthenticatedSalesOrdersIdEditRouteImport
      parentRoute: typeof AuthenticatedSalesOrdersIdRoute
    }
  }
}

interface AuthenticatedDeliveryRouteChildren {
  AuthenticatedDeliveryIdRoute: typeof AuthenticatedDeliveryIdRoute
  AuthenticatedDeliveryScheduleRoute: typeof AuthenticatedDeliveryScheduleRoute
}

const AuthenticatedDeliveryRouteChildren: AuthenticatedDeliveryRouteChildren = {
  AuthenticatedDeliveryIdRoute: AuthenticatedDeliveryIdRoute,
  AuthenticatedDeliveryScheduleRoute: AuthenticatedDeliveryScheduleRoute,
}

const AuthenticatedDeliveryRouteWithChildren =
  AuthenticatedDeliveryRoute._addFileChildren(
    AuthenticatedDeliveryRouteChildren,
  )

interface AuthenticatedEngineeringRouteChildren {
  AuthenticatedEngineeringIdRoute: typeof AuthenticatedEngineeringIdRoute
  AuthenticatedEngineeringWorkloadRoute: typeof AuthenticatedEngineeringWorkloadRoute
}

const AuthenticatedEngineeringRouteChildren: AuthenticatedEngineeringRouteChildren =
  {
    AuthenticatedEngineeringIdRoute: AuthenticatedEngineeringIdRoute,
    AuthenticatedEngineeringWorkloadRoute:
      AuthenticatedEngineeringWorkloadRoute,
  }

const AuthenticatedEngineeringRouteWithChildren =
  AuthenticatedEngineeringRoute._addFileChildren(
    AuthenticatedEngineeringRouteChildren,
  )

interface AuthenticatedSalesOrdersIdRouteChildren {
  AuthenticatedSalesOrdersIdEditRoute: typeof AuthenticatedSalesOrdersIdEditRoute
}

const AuthenticatedSalesOrdersIdRouteChildren: AuthenticatedSalesOrdersIdRouteChildren =
  {
    AuthenticatedSalesOrdersIdEditRoute: AuthenticatedSalesOrdersIdEditRoute,
  }

const AuthenticatedSalesOrdersIdRouteWithChildren =
  AuthenticatedSalesOrdersIdRoute._addFileChildren(
    AuthenticatedSalesOrdersIdRouteChildren,
  )

interface AuthenticatedSalesOrdersRouteChildren {
  AuthenticatedSalesOrdersIdRoute: typeof AuthenticatedSalesOrdersIdRouteWithChildren
  AuthenticatedSalesOrdersNewRoute: typeof AuthenticatedSalesOrdersNewRoute
}

const AuthenticatedSalesOrdersRouteChildren: AuthenticatedSalesOrdersRouteChildren =
  {
    AuthenticatedSalesOrdersIdRoute:
      AuthenticatedSalesOrdersIdRouteWithChildren,
    AuthenticatedSalesOrdersNewRoute: AuthenticatedSalesOrdersNewRoute,
  }

const AuthenticatedSalesOrdersRouteWithChildren =
  AuthenticatedSalesOrdersRoute._addFileChildren(
    AuthenticatedSalesOrdersRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDeliveryRoute: typeof AuthenticatedDeliveryRouteWithChildren
  AuthenticatedEngineeringRoute: typeof AuthenticatedEngineeringRouteWithChildren
  AuthenticatedMaterialRoute: typeof AuthenticatedMaterialRoute
  AuthenticatedOperatorsRoute: typeof AuthenticatedOperatorsRoute
  AuthenticatedProductionRoute: typeof AuthenticatedProductionRoute
  AuthenticatedProductionPlanningRoute: typeof AuthenticatedProductionPlanningRoute
  AuthenticatedQcRoute: typeof AuthenticatedQcRoute
  AuthenticatedSalesOrdersRoute: typeof AuthenticatedSalesOrdersRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDeliveryRoute: AuthenticatedDeliveryRouteWithChildren,
  AuthenticatedEngineeringRoute: AuthenticatedEngineeringRouteWithChildren,
  AuthenticatedMaterialRoute: AuthenticatedMaterialRoute,
  AuthenticatedOperatorsRoute: AuthenticatedOperatorsRoute,
  AuthenticatedProductionRoute: AuthenticatedProductionRoute,
  AuthenticatedProductionPlanningRoute: AuthenticatedProductionPlanningRoute,
  AuthenticatedQcRoute: AuthenticatedQcRoute,
  AuthenticatedSalesOrdersRoute: AuthenticatedSalesOrdersRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
